### ISSUE TITLE
violations_dat.Rds does not have filtered inspections, but all inspects

### ISSUE THREAD

**Issue by cash** [Chicago/food-inspections-evaluation#82]
Looks like the filter_foodInspect function was added after the violations_dat.Rds file was created.

For example:
```R
> inspections <- readRDS("food_inspections.Rds")
> violations <- readRDS("violation_dat.Rds")
> inspections[132,c("Inspection_ID", "Inspection_Type")]
    Inspection_ID Inspection_Type
132         58241        No Entry
> violations[132,]
    criticalCount seriousCount minorCount Inspection_ID
132             0            0          0         58241
```
A "No Entry" value would have been filtered out with the current code.

It's a little confusing to jump in following the README in CODE and get different results than what is in DATA.

**Comment by geneorama** [comment]
Yes, that is confusing, and it's pretty amazing to me that you noticed it and figured it out.

I removed the line that does the filtering, since that would have the least impact on the project.  I thanked you in the commit message. 

I must have added the filtering line at some point to save run time, but it doesn't hurt to have full unfiltered violation data.

I'll close this issue, but please let me know if you see any other related problems.

Also, if you'd ever like to submit a pull request, please accept the contributor agreement.  We need to have that to accept any code contributions.

Thank you very much for your input.

Gene
